version: '3'
services:

  database-postgres:
    image: "postgres:latest"
    restart: always
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        DATABASE_PORT: 5432
    networks:
        - application

  application-go:
    build: ./backend
    container_name: app-go
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydb
        DATABASE_PORT: 5432
    ports:
      - 8080:8080
    depends_on:
      - database-postgres
    networks:
        - application

  application-ui:
    build: ./frontend
    container_name: reactjs-ui
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - application-go
    networks:
        - application

volumes:
  postgres-data:

networks:
  application:
